name: events_finder
publish_to: "none"
description: Open Mic / Jam / Gig finder – Flutter + Firebase + Riverpod

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management & routing
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.1

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  # google_sign_in: ^7.1.1
  google_sign_in: ^5.4.0

  # Geolocation & mapping
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # Networking
  http: ^1.5.0
  what3words: ^3.2.0

  # Local storage
  shared_preferences: ^2.5.3

  # UI
  gap: ^3.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"