// import 'package:firebase_core/firebase_core.dart';
// import '../firebase_options.dart'; // generated by flutterfire

// class FirebaseService {
//   static Future<void> init() async {
//     await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
//   }
// }

import 'package:firebase_core/firebase_core.dart';
//  import 'firebase_options.dart';
import 'package:events_finder/firebase_options.dart';

class FirebaseService {
  static Future<void> init() async {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    // You can also print other options if you want:
    // print('Firebase initialized (projectId=${Firebase.app().options.projectId})');
  }
}
