// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_48SoDWq81RE600ZlIwhH08G9SnLBAGs',
    appId: '1:813261390073:web:410f5fdf9d177b4df9e228',
    messagingSenderId: '813261390073',
    projectId: 'venuelookup-75152',
    authDomain: 'venuelookup-75152.firebaseapp.com',
    storageBucket: 'venuelookup-75152.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7C4KPvJ7LUTjEyDe7fVwiFP27f-Ci8tY',
    appId: '1:813261390073:android:e38719e7654004bcf9e228',
    messagingSenderId: '813261390073',
    projectId: 'venuelookup-75152',
    storageBucket: 'venuelookup-75152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhhc61DVDX0EHAdUc5mZIrK87DtHsPKNY',
    appId: '1:813261390073:ios:0b2a260b43e8b92cf9e228',
    messagingSenderId: '813261390073',
    projectId: 'venuelookup-75152',
    storageBucket: 'venuelookup-75152.firebasestorage.app',
    iosBundleId: 'com.example.findanevent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhhc61DVDX0EHAdUc5mZIrK87DtHsPKNY',
    appId: '1:813261390073:ios:0b2a260b43e8b92cf9e228',
    messagingSenderId: '813261390073',
    projectId: 'venuelookup-75152',
    storageBucket: 'venuelookup-75152.firebasestorage.app',
    iosBundleId: 'com.example.findanevent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_48SoDWq81RE600ZlIwhH08G9SnLBAGs',
    appId: '1:813261390073:web:343909c031e9392ff9e228',
    messagingSenderId: '813261390073',
    projectId: 'venuelookup-75152',
    authDomain: 'venuelookup-75152.firebaseapp.com',
    storageBucket: 'venuelookup-75152.firebasestorage.app',
  );
}
